function p = gan_parameters()
%GAN_PARAMETERS  Parameter set for the Stage-1 GaN HEMT device digital twin.
%
%   p = GAN_PARAMETERS() returns every parameter required by the twin,
%   together with a provenance record for each parameter group.
%
%   Target device : onsemi NTLEF2D2N15GN1 / NTLEF2D2N15GN1/D
%                   150 V enhancement-mode AlGaN/GaN HEMT, PDSO-N8
%   Source        : onsemi datasheet, revision P1 (preliminary), July 2026
%   Scope         : Stage 1 only - device twin plus standardized data
%                   generation. No degradation, health-state, DHI or RUL
%                   modelling is performed or implied.
%
%   PROVENANCE TAGS
%     'DATASET'        value printed in the datasheet
%     'DATASET_CALC'   computed from datasheet values only
%     'MODEL'          shape parameter solved so the model reproduces
%                      datasheet measurements
%     'ASSUMED'        not present in the datasheet; documented choice
%
%   Every value below carries a tag in p.provenance.

p = struct();

%% ------------------------------------------------------------------------
%  Metadata
%  ------------------------------------------------------------------------
p.meta = struct( ...
    'stage',                 'Stage 1', ...
    'scope',                 'GaN HEMT device digital twin and standardized data generation', ...
    'model_name',            'GaN HEMT device digital twin', ...
    'model_version',         'stage1-device-twin-1.0.0', ...
    'manufacturer',          'onsemi', ...
    'device_part_number',    'NTLEF2D2N15GN1', ...
    'publication_order',     'NTLEF2D2N15GN1/D', ...
    'technology',            'enhancement-mode AlGaN/GaN HEMT', ...
    'package',               'PDSO-N8, 5.0 mm x 6.0 mm x 0.87 mm', ...
    'datasheet_revision',    'P1 (preliminary), July 2026', ...
    'datasheet_pages',       6, ...
    'degradation_modelled',  false, ...
    'health_state_modelled', false);

%% ------------------------------------------------------------------------
%  Absolute maximum ratings  (all DATASET)
%  ------------------------------------------------------------------------
p.ratings = struct( ...
    'vds_drain_source_V',    150, ...
    'vgs_min_V',             -4, ...
    'vgs_max_V',             6, ...
    'vgs_pulse_max_V',       6.5, ...
    'id_continuous_25C_A',   115, ...
    'id_pulse_25C_A',        840, ...
    'id_pulse_150C_A',       640, ...
    'pd_total_W',            NaN, ...
    'tj_min_C',              -55, ...
    'tj_max_C',              150, ...
    'tstg_min_C',            -55, ...
    'tstg_max_C',            150, ...
    'tsld_max_C',            260);

%% ------------------------------------------------------------------------
%  DC specification points  (DATASET)
%  ------------------------------------------------------------------------
p.dc = struct( ...
    'rds_on_typ_ohm',        1.6e-3, ...
    'rds_on_max_ohm',        2.2e-3, ...
    'rds_on_vgs_V',          5, ...
    'rds_on_ids_A',          50, ...
    'vgs_th_min_V',          1.1, ...
    'vgs_th_ids_A',          10e-3, ...
    'idss_max_25C_A',        4e-6, ...
    'idss_max_125C_A',       60e-6, ...
    'idss_vds_V',            150, ...
    'igss_max_25C_A',        2e-6, ...
    'igss_max_125C_A',       40e-6, ...
    'igss_vgs_V',            6, ...
    'br_dss_min_V',          150);

% RON is measured at VGS = 5 V and IDS = 50 A. The drain-source voltage
% implied by that condition is VDS = RON * IDS.  (DATASET_CALC)
p.dc.vds_ron_spec_V = p.dc.rds_on_typ_ohm * p.dc.rds_on_ids_A;   % 0.08 V

% FOM-QG cross-check: the datasheet prints FOM-QG = 54.4 nC*mOhm, which is
% exactly QG * RDS(on) = 34 nC * 1.6 mOhm. This corroborates QG = 34 nC.
p.dc.fom_qg_nC_mohm = 54.4;
p.dc.fom_qg_from_qg_and_ron = 34e-9 * p.dc.rds_on_typ_ohm * 1e12;   % 54.4

%% ------------------------------------------------------------------------
%  Capacitance specification points  (DATASET, all at VDS = 75 V, VGS = 0 V,
%  f = 1 MHz)
%  ------------------------------------------------------------------------
p.caps = struct( ...
    'vds_test_V',            75, ...
    'vgs_test_V',            0, ...
    'f_test_Hz',             1e6, ...
    'ciss_F',                4820e-12, ...
    'coss_F',                1150e-12, ...
    'crss_F',                19e-12);

% The three capacitances are mutually consistent under the standard
% relations  Ciss = Cgs + 2*Cgd,  Coss = Cds + Cgd,  Crss = Cgd.
% Solving them gives unique device capacitances (DATASET_CALC).
p.caps.cgd_ref_F  = p.caps.crss_F;
p.caps.cgs_ref_F  = p.caps.ciss_F - 2*p.caps.cgd_ref_F;   % 4782 pF
p.caps.cds_ref_F  = p.caps.coss_F - p.caps.cgd_ref_F;     % 1131 pF

%% ------------------------------------------------------------------------
%  Charge specification points  (DATASET)
%  ------------------------------------------------------------------------
p.charge = struct( ...
    'qg_nC',                 34e-9, ...
    'qgs_nC',                10.8e-9, ...
    'qgd_nC',                4.7e-9, ...
    'qoss_nC',               187e-9, ...
    'qgd_vds_V',             75, ...
    'qgd_ids_A',             50, ...
    'vgs_charge_start_V',    0, ...
    'vgs_charge_end_V',      5);

% INTEGRITY CHECK. The charge table is internally inconsistent: the printed
% sub-charges do not sum to the printed total gate charge. QG itself is
% corroborated by the FOM-QG entry, so the inconsistency is attributed to
% QGS and/or QGD. This is a DATASET finding, not a model error.
p.charge.qgs_plus_qgd_nC = p.charge.qgs_nC + p.charge.qgd_nC;   % 15.5 nC
p.charge.qg_is_consistent = abs(p.charge.qgs_plus_qgd_nC - p.charge.qg_nC) < 0.05*p.charge.qg_nC;

%% ------------------------------------------------------------------------
%  Capacitance / charge model extraction
%
%  Every junction capacitance is represented by the standard depletion form
%
%       C(V) = C0 / (1 + |V| / Vj)
%
%  whose integral is the transferred charge
%
%       Q(V) = C0 * Vj * ln(1 + |V| / Vj)  =  C(Vref) * (Vj + Vref) * ln(1 + Vref/Vj)
%
%  Because both C(Vref) and the integral charge are given by the datasheet,
%  Vj and C0 follow uniquely from two independent constraints and are solved
%  numerically here. No shape parameter is free.
%  ------------------------------------------------------------------------
% Coss: C(75 V) = 1150 pF  and  Qoss = 187 nC over 0 -> 75 V
[p.caps.coss0_F, p.caps.vjc_V] = solve_depletion( ...
    p.caps.coss_F, p.caps.vds_test_V, p.charge.qoss_nC);

% Cgd: C(75 V) = Crss = 19 pF  and  Qgd = 4.7 nC over 0 -> 75 V
[p.caps.cgd0_F, p.caps.vjg_V] = solve_depletion( ...
    p.caps.cgd_ref_F, p.caps.vds_test_V, p.charge.qgd_nC);

% Cgs: C(0 V) = 4782 pF  and  Qgs = 10.8 nC over 0 -> 5 V
% One free shape parameter (vgsc) remains and is solved so that the integral
% reproduces the datasheet Qgs; it is tagged 'MODEL', not 'ASSUMED'.
p.caps.vgsc_V = solve_decay_scale( ...
    p.caps.cgs_ref_F, p.charge.vgs_charge_end_V, p.charge.qgs_nC);

%% ------------------------------------------------------------------------
%  Channel (DC) model extraction
%
%  Compact square-law channel with velocity saturation and output
%  conductance:
%
%      Vov    = VGS - VTH
%      Vc     = Vov/2 * (1 + tanh(Vov / (2*Vsmooth)))        smooth knee
%      Vdsat  = min(Vc, VDSAT)
%      Vdc    = min(|VDS|, Vdsat)
%      Ich    = sign(VDS) * K * (Vc*Vdc - Vdc^2/2) * (1 + |VDS|/VA)
%
%  K is fixed by the RON(on) test point (DATASET_CALC): at VGS = 5 V and
%  VDS = 80 mV the channel must pass exactly 50 A, i.e. RON = 1.6 mOhm.
%  ------------------------------------------------------------------------
vov_ron = p.dc.rds_on_vgs_V - p.dc.vgs_th_min_V;            % 3.9 V
vds_ron = p.dc.vds_ron_spec_V;                              % 0.08 V
p.model.k_amp_per_v2 = p.dc.rds_on_ids_A / ...
    (vov_ron*vds_ron - 0.5*vds_ron^2);                      % ~161.9 A/V^2

% VDSAT is chosen so the saturation current at VGS = 5 V reproduces the
% datasheet maximum pulsed drain current rating of 840 A (MODEL).
p.model.va_V   = 100;                                       % ASSUMED
p.model.vsmooth_V = 0.05;                                   % ASSUMED
p.model.vdsat_V = solve_vdsat(p.model.k_amp_per_v2, vov_ron, ...
    p.model.va_V, p.ratings.id_pulse_25C_A);

p.model.vth_V      = p.dc.vgs_th_min_V;                    % DATASET
p.model.vgs_min_V  = p.ratings.vgs_min_V;
p.model.vgs_max_V  = p.ratings.vgs_max_V;
p.model.vdss_ref_V = p.dc.br_dss_min_V;

% Leakage temperature ratio taken directly from the two datasheet IDSS
% points: 4 uA at 25 C rising to 60 uA at 125 C (DATASET_CALC).
p.model.leak_temp_ratio = p.dc.idss_max_125C_A / p.dc.idss_max_25C_A;  % 15
p.model.leak_temp_span_C = 100;
p.model.tnom_C = 25;

% Effective isolation width of the gate leakage knee. The datasheet gives
% only the maximum magnitude at VGS = 6 V, so the knee width is ASSUMED and
% the magnitude is anchored to the datasheet maximum.
p.model.vigs_iso_V = 0.5;                                   % ASSUMED
p.model.idss_A = p.dc.idss_max_25C_A;                       % DATASET
p.model.igss_A = p.dc.igss_max_25C_A;                       % DATASET

% The printed IDSS and IGSS pairs have different temperature ratios:
% IDSS is 4 uA / 60 uA (factor 15) while IGSS is 2 uA / 40 uA (factor 20).
% Applying one ratio to both would miss the IGSS maximum by 25 %.
% (CALCULATED-FROM-DATASET)
p.model.igss_temp_ratio = p.dc.igss_max_125C_A / p.dc.igss_max_25C_A;   % 20

%% ------------------------------------------------------------------------
%  Solver settings
%  ------------------------------------------------------------------------
p.solver = struct( ...
    'solver_type',          'ode3', ...
    'sample_time_s',        1e-9, ...
    'max_step_s',           1e-9, ...
    'tcase_nom_C',          25);

% ------------------------------------------------------------------------
%  Excitation profile settings (ASSUMED: purely numerical stimulus choices)
% ------------------------------------------------------------------------
p.switching = struct( ...
    'vbus_V',        100, ...
    'rload_ohm',     0.12, ...
    'vgs_on_V',      5, ...
    'vgs_off_V',     0, ...
    't_on_s',        2e-6, ...
    't_off_s',       2e-6, ...
    'n_cycles',      3, ...
    'n_rise',        20);

%% ------------------------------------------------------------------------
%  Flat parameter vector shared with the Simulink twin
%
%  Simulink cannot compile a struct-valued Constant block, so the twin
%  receives its parameters as one numeric row vector. The order below is the
%  contract between this file and create_gan_hemt_twin; the MATLAB Function
%  blocks index into it by position.
% ------------------------------------------------------------------------
p.model.vector_names = { ...
    'cgd0', 'vjg', 'coss0', 'vjc', 'cgs0', 'vgsc', 'vth', 'vgs_min', ...
    'k', 'vsmooth', 'vdsat', 'va', 'idss', 'vdss_ref', 'igss', 'vgs_max', ...
    'vigs_iso', 'leak_ratio', 'leak_span', 'tnom', 'ron_ithresh', 'igss_leak_ratio'};

p.model.vector = [ ...
    p.caps.cgd0_F,   p.caps.vjg_V,   p.caps.coss0_F,  p.caps.vjc_V, ...
    p.caps.cgs_ref_F, p.caps.vgsc_V,  p.model.vth_V,   p.model.vgs_min_V, ...
    p.model.k_amp_per_v2, p.model.vsmooth_V, p.model.vdsat_V, p.model.va_V, ...
    p.model.idss_A,  p.model.vdss_ref_V, p.model.igss_A, p.model.vgs_max_V, ...
    p.model.vigs_iso_V, p.model.leak_temp_ratio, p.model.leak_temp_span_C, ...
    p.model.tnom_C,  0.1, p.model.igss_temp_ratio];

if numel(p.model.vector) ~= numel(p.model.vector_names)
    error('gan_parameters:vectorLength', ...
        'Parameter vector has %d entries but %d names.', ...
        numel(p.model.vector), numel(p.model.vector_names));
end

%% ------------------------------------------------------------------------
%  Provenance record
% ------------------------------------------------------------------------
%  Every entry begins with one of exactly four permitted tags:
%    DATASET-DERIVED          printed directly in the datasheet
%    CALCULATED-FROM-DATASET  derived only from printed datasheet numbers
%    MANUFACTURER-DERIVED     taken from the device's described physics
%    ASSUMED                  chosen by this twin, not in the datasheet
%  Any explanation after the tag is informational only.
p.provenance = struct( ...
    'meta',                 'DATASET-DERIVED: part number, family, revision, date', ...
    'ratings',              'DATASET-DERIVED: voltage, current and power ratings', ...
    'dc',                   'DATASET-DERIVED: R&D(on), V(th), IDSS, IGSS and test conditions', ...
    'vds_ron_spec_V',       'CALCULATED-FROM-DATASET: RDS(on) * IDS = 0.08 V', ...
    'fom_qg_from_qg_and_ron','CALCULATED-FROM-DATASET: QG * RDS(on) = 54.4 nC*mOhm', ...
    'caps',                 'DATASET-DERIVED: Ciss, Coss, Crss at VDS=75 V, VGS=0 V, 1 MHz', ...
    'cgs_ref_F',            'CALCULATED-FROM-DATASET: Ciss - 2*Crss = 4782 pF', ...
    'cds_ref_F',            'CALCULATED-FROM-DATASET: Coss - Crss = 1131 pF', ...
    'charge',               'DATASET-DERIVED: QG, QGS, QGD and Qoss', ...
    'coss0_F',              'CALCULATED-FROM-DATASET: solved from Coss(75 V) and Qoss', ...
    'vjc_V',                'CALCULATED-FROM-DATASET: solved from Coss(75 V) and Qoss', ...
    'cgd0_F',               'CALCULATED-FROM-DATASET: solved from Crss(75 V) and Qgd', ...
    'vjg_V',                'CALCULATED-FROM-DATASET: solved from Crss(75 V) and Qgd', ...
    'vgsc_V',               'CALCULATED-FROM-DATASET: solved so integral Cgs dVgs equals Qgs', ...
    'k_amp_per_v2',         'CALCULATED-FROM-DATASET: from the RON(on) test point', ...
    'vdsat_V',              'CALCULATED-FROM-DATASET: solved so Id_sat(5 V) equals the ID,pulse rating', ...
    'vth_V',                'DATASET-DERIVED: gate threshold voltage', ...
    'vgs_min_V',            'DATASET-DERIVED: datasheet minimum on-state gate drive', ...
    'vgs_max_V',            'DATASET-DERIVED: datasheet maximum gate drive', ...
    'vdss_ref_V',           'DATASET-DERIVED: voltage of the printed IDSS test point', ...
    'leak_temp_ratio',      'CALCULATED-FROM-DATASET: 60 uA / 4 uA across 25-125 degC', ...
    'idss_A',               'DATASET-DERIVED: maximum IDSS at 125 degC', ...
    'igss_A',               'DATASET-DERIVED: maximum IGSS at 125 degC', ...
    'model_form',           'MANUFACTURER-DERIVED: depletion C(V) for Coss/Crss, gate-reduced Cgs, square-law channel with output conductance', ...
    'va_V',                 'ASSUMED: no output-conductance data exist in the dataset', ...
    'vsmooth_V',            'ASSUMED: numerical knee smoothing only', ...
    'vigs_iso_V',           'ASSUMED: gate-leakage knee width only', ...
    'thermal_model',        'ASSUMED: none; all thermal resistances are TBD so Tj tracks Tcase', ...
    'solver',               'ASSUMED: numerical integration settings only');

%% ------------------------------------------------------------------------
%  Known dataset defects carried forward into validation reporting
%  ------------------------------------------------------------------------
p.dataset_defects = struct( ...
    'qg_not_sum_of_parts',  true, ...
    'qg_detail',            'QGS + QGD = 15.5 nC does not equal QG = 34 nC. QG is corroborated by FOM-QG = QG*RDS(on) = 54.4 nC*mOhm.', ...
    'qgd_test_condition',   true, ...
    'qgd_detail',           'The QGD test condition VDS = 75 V with IDS = 50 A at VGS = 5 V cannot occur for this device: the twin passes far more than 50 A at that bias. The printed condition must be current limited.', ...
    'thermal_absent',       true, ...
    'thermal_detail',       'Every thermal resistance and the total power rating are printed as TBD. No thermal model is possible.', ...
    'curves_absent',       true, ...
    'curves_detail',       'The datasheet contains no ID-VDS, ID-VGS, C-V, switching or temperature characteristic curves. Model curves are predictions, not data.');

end

%% =========================================================================
function [c0, vj] = solve_depletion(cref, vref, q)
%SOLVE_DEPLETION  Recover C0 and Vj from C(Vref) and the charge up to Vref.
%   Model:  C(V) = C0/(1 + V/Vj),  Q(Vref) = C0*Vj*ln(1 + Vref/Vj)
%   Using C(Vref) = C0/(1 + Vref/Vj) the charge reduces to
%       Q(Vref) = Cref * (Vj + Vref) * ln(1 + Vref/Vj)
%          = Cref * Vref * (1 + u) * ln(1 + u) / u,      u = Vref/Vj
%   The (1+u)ln(1+u)/u factor grows without bound as u grows, so a charge
%   larger than Cref*Vref (the Vj -> infinity asymptote) is perfectly
%   solvable. The factor falls monotonically as Vj rises, hence the bracket
%   runs from a small Vj (Q too large) to a large Vj (Q too small).

if q <= 0
    error('gan_parameters:solve_depletion', ...
        'Charge must be positive to extract a depletion shape.');
end

fn = @(vj) cref * (vj + vref) * log(1 + vref/max(vj, realmin)) - q;

lo = vref * 1e-6;
hi = vref * 1e6;
vj = fzero(fn, [lo, hi]);

c0 = cref * (1 + vref/vj);
end

%% =========================================================================
function vsc = solve_decay_scale(c0, vref, q)
%SOLVE_DECAY_SCALE  Find the voltage scale of C(V) = C0/(1 + V/Vsc) so that
%   the integral charge up to vref matches q.

if q >= c0*vref
    error('gan_parameters:solve_decay_scale', ...
        'Charge %.6g nC exceeds the rectangular bound C0*Vref = %.6g nC; no positive scale exists.', ...
        q*1e9, c0*vref*1e9);
end

fn = @(vsc) c0 * vsc * log(1 + vref/max(vsc, realmin)) - q;

lo = vref * 1e-6;
hi = vref * 1e6;
nudge = 0;
while fn(lo) > 0 && nudge < 80
    lo = lo / 10;
    nudge = nudge + 1;
end
vsc = fzero(fn, [lo, hi]);
end

%% =========================================================================
function vdsat = solve_vdsat(k, vov, va, id_target)
%SOLVE_VDSAT  Pick VDSAT so the saturation current at the given overdrive
%   equals the datasheet pulsed current rating. The function is not monotonic
%   over the whole positive axis, so the larger of the two roots is used.

fn = @(v) k * (vov*v - 0.5*v^2) * (1 + v/va) - id_target;

lo = vov * 1e-3;
hi = vov;
while fn(hi) < 0
    hi = hi * 2;
end
vdsat = fzero(fn, [lo, hi]);
end